services:
  postgres:
    image: postgres:18-alpine
    container_name: recommendations_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - recommendations_network

  pghero:
    image: ankane/pghero
    container_name: recommendations_pghero
    environment:
      DATABASE_URL: "database://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - recommendations_network

  redis:
    image: redis:7-alpine
    container_name: recommendations_redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    command: cache-server --appendonly yes
    healthcheck:
      test: ["CMD", "cache-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - recommendations_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  recommendations_network:
    driver: bridge